/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gunduzhan (https://sketchfab.com/gunduzhan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nuka-cola-vending-machine-d67e3f3d1bdd4a4e8b63c489cd55a5fc
Title: Nuka Cola Vending Machine
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dispensador(props) {
  const { nodes, materials } = useGLTF('/assets/models/Dispensador/nuka_cola_vending_machine.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vending_beyaz_0.geometry}
        material={materials.beyaz}
      />
    </group>
  );
}
export default Dispensador
useGLTF.preload('/assets/models/Dispensador/nuka_cola_vending_machine.glb');