/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aullwen (https://sketchfab.com/Aullwen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-7d870e900889481395b4a575b9fa8c3e
Title: Laptop
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/assets/models/Laptop/laptop.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_ComputerFrame_0.geometry}
        material={materials.ComputerFrame}
        position={[0, 0.976, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen_ComputerScreen_0.geometry}
        material={materials.ComputerScreen}
        position={[0, 0.65, -10.3]}
        rotation={[Math.PI, 0, -Math.PI]}
        scale={[100, 100, 88.235]}
      />
    </group>
  );
}
export default Laptop
useGLTF.preload('/assets/models/Laptop/laptop.glb');