/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: quander (https://sketchfab.com/quander)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-dog-shiba-inu-9abfce885a834399b2c3ccaed51cd474
Title: Animated Dog, Shiba Inu
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Perro(props) {
  const perroRef = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/Perro/perro.gltf'
  );
  const { actions } = useAnimations(animations, perroRef);

  useEffect(()=>{
    const action = actions["0|sitting_0"]
    action.play()
    console.log(perroRef.current);
}, [])

  return (
    <group ref={perroRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="d2a6bc8fe88e4cbca4db3d181738fe46fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Light"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100} 
                  castShadow
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[735.889, 495.831, 692.579]}
                  rotation={[Math.PI, 0.756, 2.68]}
                  scale={100}
                >
                  <group name="Object_8" />
                </group>
                <group name="RootNode0">
                  <group name="geo1" />
                  <group name="skeletal3">
                    <group name="0">
                      <group name="Object_13">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                          name="Object_206"
                          geometry={nodes.Object_206.geometry}
                          material={materials.Material_0}
                          skeleton={nodes.Object_206.skeleton}
                        />
                        <group name="Object_205" />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="shiba_inu2" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
export default Perro;
useGLTF.preload('/assets/models/Perro/perro.gltf');
