/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ryoce (https://sketchfab.com/Ryoce)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/garden-set-victorian-884d585e35eb4f389b098581246ea265
Title: Garden Set Victorian
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useTexture } from "@react-three/drei";

export function Mesa(props) {
  const { nodes, materials } = useGLTF('/assets/models/Mesa/garden_set_victorian.glb');
  const PATH = "/assets/texture/metal/";

  const propsTexture = useTexture({
    map: PATH + 'metalColor.jpg',
    // displacementMap: PATH + 'woodHeight.png',
    normalMap: PATH + 'metalNormal.jpg',
    roughnessMap: PATH + 'metalRoughness.jpg',
    aoMap: PATH + 'metalAO.jpg',
  })
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.216}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            
            rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
            >
            <meshStandardMaterial {...propsTexture}/>
            </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.005"]}
            position={[0, 0, 0.6]}
            rotation={[0, 0.037, 0]}
            >
            <meshStandardMaterial {...propsTexture}/>
            </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Material.005"]}
            position={[0, 0, -0.6]}
            >
            <meshStandardMaterial {...propsTexture}/>
            </mesh>
        </group>
      </group>
    </group>
  );
}
export default Mesa;
useGLTF.preload('/assets/models/Mesa/garden_set_victorian.glb');