/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/persian-malayer-carpet-1120ca810d0c46289d3b7071103067ac
Title: Persian Malayer Carpet
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tapete(props) {
  const { nodes, materials } = useGLTF('/assets/models/Tapete/persian_malayer_carpet.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.carpet}
      />
      <group position={[-0.921, 0.001, -0.006]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
      </group>
      <group position={[0.928, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials["VELVET-GREEN__Budapest"]}
        />
      </group>
    </group>
  );
}
export default Tapete
useGLTF.preload('/assets/models/Tapete/persian_malayer_carpet.glb');
